"""Permission code constants for RBAC (must match seeded permissions in DB)."""

APPROVE_OBJECTIVES = "approve_objectives"
EDIT_OBJECTIVES = "edit_objectives"
RUN_CALIBRATION = "run_calibration"
MANAGE_SUMMARIES = "manage_summaries"
MANAGE_REWARD_POLICY = "manage_reward_policy"
MANAGE_TEMPLATES = "manage_templates"
VIEW_AUDIT_LOGS = "view_audit_logs"
MANAGE_RBAC = "manage_rbac"
MANAGE_BASELINES = "manage_baselines"
MANAGE_NOTIFICATIONS = "manage_notifications"
MANAGE_USERS = "manage_users"
MANAGE_CYCLES = "manage_cycles"
MANAGE_DIMENSIONS = "manage_dimensions"
VIEW_USERS = "view_users"
MANAGE_BEHAVIORAL = "manage_behavioral"
MANAGE_REVIEW_SESSIONS = "manage_review_sessions"
